### ISSUE TITLE
Publish 1.7.1?

### ISSUE THREAD

**Issue by sagebind** [kennytm/extprim#19]
Would it be possible to release an extprim 1.7.1 soon so that we can get #18 out there? Currently ctest is broken downstream on nightly because of this.

**Comment by kennytm** [comment]
https://crates.io/crates/extprim/1.7.1

please consider using the built-in `i128` and `u128` types instead 😕

**Comment by sagebind** [comment]
Thanks! I don't maintain ctest though, I'm just a downstream user of a ctest dependent. But I agree. :wink:
